#ifndef __CONFIG
#define __CONFIG

#define WINDOW_W 1000
#define WINDOW_H 1000
#define AMMOUNT_OF_ARROWS 51
#define BOARDER 4
#define X_WINDOW_OFFSET 850
#define Y_WINDOW_OFFSET 40

#define ARROW_WIDTH 20
#define ARROW_HEIGHT 16

#define CORDINAT_Y_OFFSET 7
#define CORDINAT_X_OFFSET 0
#define SCALE_LINE_X_HEIGHT 50
#define SCALE_LINE_X_WIDTH 3
#define SCALE_LINE_X_X_OFFSET -2
#define SCALE_LINE_X_Y_OFFSET -32
#define SCALE_LINE_Y_X_OFFSET -14
#define SCALE_LINE_Y_Y_OFFSET -5
#define SCALE_LINE_Y_HEIGHT 5
#define SCALE_LINE_Y_WIDTH 25
#define SCALE_BOARDER 50
#define SCALE_MIN_LINE_AMMOUNT 2.2
#define SCALE_TEXT_OFFSET_X_AXIS_UP 40
#define SCALE_TEXT_OFFSET_X_AXIS_DOWN 12
#define SCALE_TEXT_OFFSET_Y_AXIS 25
#define FONT_SCALE 0.7

#define CORDS_INFO_BOX_WIDTH 110
#define CORDS_INFO_BOX_HEIGHT 40
#define CORDS_INFO_BOARDER 50
#define CORDS_INFO_X_OFFSET 20
#define CORDS_INFO_Y_OFFSET 12

#define SCALE_CHANGE_RATE 1.01

#define TIME_INTERVAL 0.015
#define POINT_WIDTH 4
#define POINT_HEIGHT 4

#define INPUT_DX_X_OFFSET 100
#define INPUT_DX_Y_OFFSET 150
#define INPUT_DY_X_OFFSET 100
#define INPUT_DY_Y_OFFSET 400
#define INPUT_WIDTH 400
#define INPUT_HEIGHT 34
#define INPUT_FONT_SCALE 2
#define INPUT_BOARDER 10

#endif